### ISSUE TITLE
log spam of an error when creating a new world

### ISSUE THREAD

**Issue by TeotlXocolatl** [trollusk/Starvation#1]
So this happened:
[Error] Exception: Object reference not set to an instance of an object.
   at Starvation.ModSystemStarvation.GetRainfallAtEntity(Entity entity) in C:\Users\pawl\Sync\vintagestorymods\starvation\starvation\src\ModSystemStarvation.cs:line 303
   at Starvation.ModSystemStarvation.GetHumidityAtEntity(Entity entity) in C:\Users\pawl\Sync\vintagestorymods\starvation\starvation\src\ModSystemStarvation.cs:line 310
   at Starvation.EntityBehaviorStarve.ServerTickSlow(Single deltaTime) in C:\Users\pawl\Sync\vintagestorymods\starvation\starvation\src\EntityBehaviorStarve.cs:line 162
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()

it maked log spam, I ended up with a file of 500 mb.

**Comment by trollusk** [comment]
I've made a small change to try and prevent this, try downloading 1.0.5 from the mod site.
